Anna Oriekhova - Week3  (ex1-giveCompliments is done)
HackYourHomework/Homework-class39 pull request #16
Opened 2022-08-11 11:54 UTC by anutka2610

2022-08-13 12:15 UTC, hmiller020414 requested changes
Hi Anna,

It looks like you didn't run your tests for the homework, because you would have seen that most of these were failing. Can you please try running those and looking at my feedback to rework these? Please make sure all pass before submitting again, and message me on Slack if you have any questions!

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex1-giveCompliment.js
> +function giveCompliment(name) {
Good work!

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex2-dogYears.js
> +function calculateDogAge(dogAge) {
Can you use a template literal here, just like you did in example 1? `${dogAge * 7}`

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex3-tellFortune.js
> +function selectRandomly(array) {
Perfect!

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex3-tellFortune.js
> +  console.log
You should be returning, not console.log

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex3-tellFortune.js
> +  selectRundomly(jobTitles) +
This should have failed in the tests, because you have the function spelled wrong. Please correct to "Randomly"

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex3-tellFortune.js
> +  ('You will be a' +
Please try using a template literal here

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex4-shoppingCart.js
> +  return `You bought ${shoppingCart.join(',')}!`;
Your return statement in this function on line 36 is perfect. Don't change that! Use this return statement to help your clean up example 3

However, let's see how we can simplify the rest of the function.

First, your first if statement isn't necessary. Let's check to see the opposite... does item exist? If (item) What do you do if item exists? You push it to the shopping cart!

If it doesn't exist, it will just return your return statement, which is why you don't need to write a condition for that!

Now what you have is if item exists, add it to the cart. Your next if statement is unrelated to the first one. So you don't need an else if, you need another if. If shoppingCart.length > 3 (you have 2 written, but if you check the instructions, you'll notice it should be 3). If length is greater than 3, shift.

Finally, your return.

Can you try rewriting this according to these instructions? Let me know if you have questions or want something explained more!

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex5-shoppingCartPure.js
> +function addToShoppingCart(shopingCart, grocery) {
This is using the exact same logic as example 4, but you can make this much simpler. In fact, in its best state, this can be a 1 line return!

Did you learn a function to cut an array into only a certain number of items?

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex6-totalCost.js
>  function test1() {
You need to write the tests for this example.

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex6-totalCost.js
> +function calculateTotalPrice() {
Your function should have a parameter, and the logic of valueP should be inside the function. You don't know that you will also be using cartForParty as your input. Your function should work for any cart.

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex7-mindPrivacy.js
> +  const newArray = employeeRecords.map ((employeeRecords)=>(
Good work using a map! Can you try using object destructuring?

2022-08-13 12:15 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex6-totalCost.js
>  function test1() {
For the first one, you should have a variable that is set to however long the list of parameters should be. It tells you the answer on line 53. Then. console.assert that that variable is equal to the function.length

For the second test, you should add up your cart items yourself and set that as your expected value. Then set another variable equal to the return of your function. Finally, console.assert that those 2 values are equal

2022-08-16 07:32 UTC, hmiller020414 commented on 1-JavaScript/Week3/homework/ex2-dogYears.js
> +return `Your doggie is ${dogAge} years old in dog years!`;
Good, but you want to return ageDog, not dogAge

2022-08-16 08:30 UTC, anutka2610 commented on 1-JavaScript/Week3/homework/ex2-dogYears.js
> +return `Your doggie is ${dogAge} years old in dog years!`;
yes, it was stupid) Thank you

2022-08-21 16:05 UTC, hmiller020414 commented
Hi Anna,

Great updates! I only had a few pieces of feedback about exercise 6, but I think you understand what is going on. I am going to approve, let me know if you have questions about 6

2023-01-26 10:21 UTC, closed without merging