Api week1 smith
HackYourHomework/Homework-class39 pull request #55
Opened 2022-09-13 11:18 UTC by asksmith

2022-09-16 08:02 UTC, remarcmij requested changes
Hi @asksmith, good work (but please note my message in the class39 channel about the old homework).

Please fix the omission in ex1. Other than that just some suggestions. Also, check your Prettier setup.

2022-09-16 08:22 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +  );
I'm missing the requested explanation:

- You may also notice that, in the case of a rejected promise, dice that have not yet finished their roll continue to do so. Can you explain why? Please add your answer as a comment to the end of the exercise file.

2022-09-16 22:17 UTC, asksmith commented
I've fix all up

2022-09-19 09:26 UTC, remarcmij approved these changes
Hi @asksmith, well done, I can approve your PR now. I still have some comments but no need for a new review round.

Good luck with the project!

2022-09-19 09:26 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex3-rollDie.js
> + **
That's what you observe, but not an explanation why this happens. The key point here is that the first call to either `resolve()` or `reject()` settles the promise to its final value. A subsequent call to either `resolve()` or `reject()` will not change the settled outcome.

2022-09-19 09:26 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
> +  }
While the test succeeds your code does not run when used by itself. In that case your `rollDice()` function is never called (you removed the `main()` function).

Your solution should work with the original `main()` function when executed directly (not as a test).

2022-09-19 09:26 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
> +  } else {
While I commend you for your clever recursive solution it at the same time requires me to do a "double (or) triple take": I need to go over your code several times to understand how it works. Luckily `async/await` can eliminate the need for recursion like this (week 2 stuff).

Note that you don't need an `else` after a return.

2022-11-02 21:29 UTC, closed without merging