Wael abuRayya-w1-usingAPIs
HackYourHomework/Homework-class39 pull request #65
Opened 2022-09-16 02:55 UTC by wael35nl

I closed my first pull request and opened this to make sure the changes in here will be only the using APIs homework files, and nothing from before.

2022-09-16 10:19 UTC, ObadaMoustafa requested changes
Hi Wael I see that you didn't make any test for your homework so please do all tests and make sure that they all passes and send to me PM to review the homework

- also In your PR now while you're reading my comment you can see above `changed files` tab .. click it and see on your left hand that all folders of Browsers module are included as well. So please put this point into your consideration while doing PR for next week's homework. You need to switch to the main branch first .. then do the new branch for the new homework.

2022-09-16 17:14 UTC, wael35nl commented
Hello Obada,

They do all pass the tests but after I did the pull request I noticed the problem that it contains all the files changed also from before, so I did the following:

I saved the solutions in an external folder before I close the pull request and delete the branch, then I created a new branch and made a new pull request without this week’s solutions, then I just pasted the solutions again and pushed them ( without redoing the tests ) as one new commit, so you can view only these from it.

Now I did run the tests and re-push them within one new commit again, that is: ([running the tests](https://github.com/HackYourHomework/Homework-class39/pull/65/commits/de9c40c399e6f5889a1afd7b2c5cc46905f526fd))

And certainly, you're right, I need to avoid all of this next time &#128516;

Appreciate your help, thanks.

2022-09-17 00:52 UTC, ObadaMoustafa approved these changes
Good job Wael. seems you got familiar with promises really fast

2022-09-17 00:52 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +    });
cool

2022-09-17 00:52 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +  });
nice

2022-09-17 00:52 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week1/homework/ex3-rollDie.js
> +    });
👍👍

2022-09-17 00:52 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
> +    })
great and when you have time you can think about how to refactor your code to avoid duplicating this code for 4 time 
```js
.then((value) => {
      results.push(value);
      return rollDie(2);
    })
```

2022-12-04 02:58 UTC, closed without merging