Wael AbuRayya-UsingApis-W2
HackYourHomework/Homework-class39 pull request #77
Opened 2022-09-22 05:00 UTC by wael35nl

2022-09-24 17:47 UTC, ObadaMoustafa requested changes
Hey Wael good job .. I wrote you some comments below and of course you're welcome to contact me if you face any difficulties

2022-09-24 17:47 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +  }
what meaning of `if (response)` ? it's always will be true. please give it another shot .. also let's think about why we need this `requestData` function? because we need it to be usable and to use  it's returning data after calling it without doing all these steps every time.. so we need this function to return the ready-to-use `data` or an `error`

✏modify✏

2022-09-24 17:47 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +    });
first why we made `requestData` function ? and if we will not use it what will happen if you get some error ?
✏modify✏

2022-09-24 17:47 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +    await requestData('https://xkcd.now.sh/?comic=latest').then((data) => {
I think after modification you need to refactor this as well
✏modify✏

2022-09-24 17:47 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  throw new Error('Request failed!');
> this comment is about whole ex2 not only this block of code 

actually Wael it looks very nice but sorry man it's totally different of what we need to teach you from this homework .. I guess you missed to read the [Readme ](https://github.com/HackYourHomework/Homework-class39/blob/main/3-UsingAPIs/Week2/README.md) file of this week because it has all details.

but again really you app looks very nice but sorry you have to repeat it
✏modify✏

2022-09-24 17:47 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex3-rollAnAce.js
> +  return value;
exactly 👍

2022-09-24 17:47 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex3-rollAnAce.js
> +      console.log('Resolved!', results)
it shouldn't be like that you're mixing the promise chain with async/await

✏modify✏

2022-09-24 17:47 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex4-diceRace.js
> +    await rollDice().then((results) => console.log('Resolved!', results));
the same about mixing promise chain with async/await
✏modify✏

2022-09-30 01:53 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +  }
thanks to your good explanation, I adjusted my solution, hope it's now right...

2022-09-30 01:55 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +    });
modified

2022-09-30 02:07 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +    await requestData('https://xkcd.now.sh/?comic=latest').then((data) => {
I just removed the curly braces from the then, while it worked either with (async/await , try/catch) or without (async/await) but with (then/catch)...
did I get it?

2022-09-30 02:15 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  throw new Error('Request failed!');
I actually did read the whole readme file, but from vscode where I didn't see the explaining gif 😐
I will redo it 👍🏽

2022-09-30 02:22 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex3-rollAnAce.js
> +      console.log('Resolved!', results)
Just like exercise one, do you mean that I shall not use async/await but only then and catch?

2022-09-30 02:23 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex4-diceRace.js
> +    await rollDice().then((results) => console.log('Resolved!', results));
Done!

2022-09-30 05:37 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +  }
Thanks to your explanation, exercise modified.

2022-09-30 05:41 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  throw new Error('Request failed!');
Thank you for the nice words.
I actually did read the whole readme file but from vscode where I couldn't see the explaining gif.
I will do it again...

2022-09-30 05:44 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex3-rollAnAce.js
> +      console.log('Resolved!', results)
Done!

2022-09-30 05:44 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex4-diceRace.js
> +    await rollDice().then((results) => console.log('Resolved!', results));
Done!

2022-10-01 08:09 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  throw new Error('Request failed!');
Now it's done, I appreciate your guide to making me learn a lot about select and option tags...

2022-10-05 08:20 UTC, ObadaMoustafa approved these changes
Great job Wael .. I see that you became more familiar with try/catch .. async/await .. that's nice
I wrote some comments for you if you have time you can do it but it's not mandatory.

congratulations and good luck with Node.js module

2022-10-05 08:20 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +  if (response.ok && response.status >= 200) {
`response.status >= 200` so what if it's 404 (NOT found) or 500 (internal Error) ??
it's enough to use  `response.ok` because if it's true then you have a response .. or if you need to make more control over it you can read [this page](https://restfulapi.net/http-status-codes/) to know what every status code means

📝advise📝

2022-10-05 08:20 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    img.src = data.sprites.other.dream_world.front_default;
I want you to get the higher quality photo
you can find it inside sprites>other>official-artwork .. just to make sure that you can access objects in different ways

📝better to modify📝

2022-10-05 08:20 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex3-rollAnAce.js
> +    console.log('Resolved!', results);
perfect 👌

2022-10-05 08:20 UTC, ObadaMoustafa commented on 3-UsingAPIs/Week2/homework/ex4-diceRace.js
> +    console.log('Resolved!', results);
exactly

2022-10-05 09:09 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +  if (response.ok && response.status >= 200) {
A great resource for status code and a nice spot to think about (what if > 200 means 404?)
I will adjust it.
thanks

2022-10-05 18:09 UTC, wael35nl commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    img.src = data.sprites.other.dream_world.front_default;
so it is: other["official-artwork"].front_default👍🏽
Done

2022-10-05 18:13 UTC, wael35nl commented
I appreciate your effort, good luck to you too 🎉

2022-12-04 02:58 UTC, closed without merging